spring:
  application:
    name: TicketWar
  config:
    import:
      - classpath:/yaml/application-local.yml
      # - classpath:/yaml/application-dev.yml
      # - classpath:/yaml/application-prod.yml
  profiles:
    group:
      profile_group_1: local, log # 설정 = local.yml + log.yml
      # profile_group_2: dev ...
  # --------------------------------
    active: profile_group_1
  # --------------------------------
