spring:
  config:
    import:
      - classpath:/yaml/application-local.yml
      - classpath:/yaml/application-dev.yml
      - classpath:/yaml/application-prod.yml
      - classpath:/yaml/application-log.yml
  application:
    name: TicketWar

  profiles:
    group:
      local: application-local, application-log
      dev: application-dev, application-log
      prod: application-prod
    #######################
    active: local
    #######################
