spring:
  config:
    import:
      - classpath:/yaml/local.yml
      - classpath:/yaml/dev.yml
      - classpath:/yaml/prod.yml
      - classpath:/yaml/log.yml
  application:
    name: TicketWar
  profiles:
    group:
      profile_local : local, log
      profile_dev : dev, log
      profile_prod : prod
    #######################
    active: profile_local
    #######################
