# local environment settings
server:
  port: 8080

spring:
#  sql:
#    init:
#     schema-locations: classpath:sql/schema.sql
#     data-locations: classpath:sql/data.sql
  config:
    activate:
      on-profile: local
  h2:
    console:
      enabled: true
      path: /h2-console # = default value
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1;MODE=MySQL
    username: sa
    password: