# ---------------------------------
# local environment settings
# ---------------------------------
server:
  port: 8080 # localhost

spring:
  config:
    activate:
      on-profile: local
  h2:
    console:
      enabled: true
      path: /h2-console # = default value
  jpa:
    hibernate:
      ddl-auto: create-drop
#      jdbc:
#        time_zone: UTC # NOTE: is this OK?
#        useLegacyDatetimeCode: false
  datasource:
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: root
    password: # enter your root password if set.
